// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: '1:your-app-id:web:your-web-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    measurementId: 'G-your-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: '1:your-app-id:android:your-android-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:your-app-id:ios:your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.spider-doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:your-app-id:ios:your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.spider-doctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:your-app-id:web:your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    measurementId: 'G-your-measurement-id',
  );
}
